<a href="https://colab.research.google.com/github/Nick-FF/Python_Lib/blob/lesson1/Lib_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Работа с Numpy


In [ ]:
Задание 1 

In [36]:
import numpy as np


In [3]:
c= np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]])
a=c.T
a,c

(array([[ 1,  6],
        [ 2,  8],
        [ 3, 11],
        [ 3, 10],
        [ 1,  7]]), array([[ 1,  2,  3,  3,  1],
        [ 6,  8, 11, 10,  7]]))

In [4]:
mean_a = np.array(a.mean(axis=0))
mean_a

array([2. , 8.4])

Задание 2


In [5]:
d= a-mean_a
d



array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание3


In [35]:
a_centered_sp = sum(map(lambda x, y: x*y, mean_a))
a_centered_sp


TypeError: ignored

In [6]:
e=d.T
e


array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [13]:
a_centered_sp=sum(e[0]*e[1])/(len(e)*len(e[0])-1)
a_centered_sp

0.8888888888888888

Задание 4


In [17]:
cov = np.cov(c, ddof=1)
cov

array([[1. , 2. ],
       [2. , 4.3]])

###Библиотека Pandas

In [2]:
import pandas as pd


In [3]:
d_a={
  "authors_id": [1,2,3],
  "authors_name": ['Тургенев', 'Чехов', 'Островский']}
authors=pd.DataFrame(d_a)
authors

authors_id authors_name
0           1     Тургенев
1           2        Чехов
2           3   Островский

In [4]:
d_b={
  "authors_id": [1, 1, 1, 2, 2, 3, 3],
  "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
  "price": [450, 300, 350, 500, 450, 370, 290]}
books=pd.DataFrame(d_b)
books

authors_id            book_title  price
0           1           Отцы и дети    450
1           1                 Рудин    300
2           1     Дворянское гнездо    350
3           2      Толстый и тонкий    500
4           2       Дама с собачкой    450
5           3                 Гроза    370
6           3  Таланты и поклонники    290

In [5]:
authors_price = pd.merge(authors, books, on='authors_id', how='outer')
authors_price

authors_id authors_name            book_title  price
0           1     Тургенев           Отцы и дети    450
1           1     Тургенев                 Рудин    300
2           1     Тургенев     Дворянское гнездо    350
3           2        Чехов      Толстый и тонкий    500
4           2        Чехов       Дама с собачкой    450
5           3   Островский                 Гроза    370
6           3   Островский  Таланты и поклонники    290

In [6]:
authors_price.sort_values(by="price", inplace=True)
authors_price

authors_id authors_name            book_title  price
6           3   Островский  Таланты и поклонники    290
1           1     Тургенев                 Рудин    300
2           1     Тургенев     Дворянское гнездо    350
5           3   Островский                 Гроза    370
0           1     Тургенев           Отцы и дети    450
4           2        Чехов       Дама с собачкой    450
3           2        Чехов      Толстый и тонкий    500

In [31]:
authors_price["cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [32]:
gb_an=authors_price.copy()
gb_an["max_price"] = gb_an["price"]
gb_an["min_price"] = gb_an["price"]
gb_an["mean_price"] = gb_an["price"]
authors_stat = gb_an.groupby("authors_name")
authors_stat.agg({"max_price": "max", "min_price": "min", "mean_price": "mean"})


max_price  min_price  mean_price
authors_name                                  
Островский          370        290  330.000000
Тургенев            450        300  366.666667
Чехов               500        450  475.000000

In [37]:
#?pd.pivot_table
book_info = pd.pivot_table(authors_price, values='price', index=['authors_name'],columns=['cover'], aggfunc=np.sum)
book_info

cover         мягкая  твердая
authors_name                 
Островский       NaN    660.0
Тургенев       650.0    450.0
Чехов          950.0      NaN

In [38]:
book_info.to_pickle("book_info.pkl")

In [39]:
book_info2 = pd.read_pickle("book_info.pkl")
book_info2

cover         мягкая  твердая
authors_name                 
Островский       NaN    660.0
Тургенев       650.0    450.0
Чехов          950.0      NaN