<a href="https://colab.research.google.com/github/Nick-FF/Python_Lib/blob/lesson2/Num_Pand_repeat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a= np.arange(12,24,1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [ ]:
b=np.linspace(12,23,12)
b

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [ ]:
a1=[np.random.choice(a, (i+1,i+2)) for i in range(1,6)]
a1

[array([[12, 19, 17],
        [21, 15, 13]]), array([[17, 23, 17, 21],
        [19, 22, 21, 19],
        [17, 15, 16, 19]]), array([[22, 12, 17, 18, 17],
        [19, 18, 21, 17, 21],
        [22, 23, 12, 13, 12],
        [17, 20, 21, 18, 19]]), array([[13, 23, 21, 21, 13, 19],
        [18, 20, 12, 15, 19, 21],
        [13, 14, 18, 13, 21, 20],
        [15, 15, 17, 20, 14, 13],
        [18, 17, 12, 17, 18, 14]]), array([[13, 18, 16, 21, 18, 12, 20],
        [14, 14, 15, 17, 21, 21, 18],
        [20, 18, 20, 18, 14, 23, 17],
        [22, 16, 17, 21, 12, 12, 16],
        [14, 13, 19, 14, 20, 15, 15],
        [16, 22, 12, 15, 21, 16, 14]])]

In [ ]:
a1=[a.reshape(i,int(len(a)/i)) for i in range(2,13) if len(a)%i==0]
a1

[array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]), array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]), array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]])]

In [ ]:
a1=[a.reshape(i,-1) for i in range(2,13) if len(a)%i==0]
a1

[array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]), array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]), array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]])]

Массив состоящий из 1 столбца и 12 строк нельзя назвать одномерным

задание 5 

задание 6

In [ ]:
a= np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [ ]:
b= np.arange(20,1,-2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

массивы одинаковые

In [ ]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

In [ ]:
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.size(v)

10

In [ ]:
l= np.arange(0,12,1)
l

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a = l.reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
at=a.T
at

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [ ]:
b=np.dot(a,at)
b

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [ ]:
import scipy.linalg


In [ ]:
d_inv= np.linalg.inv(b)
d_inv

LinAlgError: ignored